import * as stylex from "@stylexjs/stylex";

export const scrollMarginTop = stylex.create({
  _0: { scrollMarginTop: "0" },
  _0_125rem: { scrollMarginTop: "0.125rem" },
  _0_25rem: { scrollMarginTop: "0.25rem" },
  _0_375rem: { scrollMarginTop: "0.375rem" },
  _0_5rem: { scrollMarginTop: "0.5rem" },
  _0_625rem: { scrollMarginTop: "0.625rem" },
  _0_75rem: { scrollMarginTop: "0.75rem" },
  _0_875rem: { scrollMarginTop: "0.875rem" },
  _1_25rem: { scrollMarginTop: "1.25rem" },
  _1_5rem: { scrollMarginTop: "1.5rem" },
  _1_75rem: { scrollMarginTop: "1.75rem" },
  _10rem: { scrollMarginTop: "10rem" },
  _11rem: { scrollMarginTop: "11rem" },
  _12rem: { scrollMarginTop: "12rem" },
  _13rem: { scrollMarginTop: "13rem" },
  _14rem: { scrollMarginTop: "14rem" },
  _15rem: { scrollMarginTop: "15rem" },
  _16rem: { scrollMarginTop: "16rem" },
  _18rem: { scrollMarginTop: "18rem" },
  _1px: { scrollMarginTop: "1px" },
  _1rem: { scrollMarginTop: "1rem" },
  _2_25rem: { scrollMarginTop: "2.25rem" },
  _2_5rem: { scrollMarginTop: "2.5rem" },
  _2_75rem: { scrollMarginTop: "2.75rem" },
  _20rem: { scrollMarginTop: "20rem" },
  _24rem: { scrollMarginTop: "24rem" },
  _2rem: { scrollMarginTop: "2rem" },
  _3_5rem: { scrollMarginTop: "3.5rem" },
  _3rem: { scrollMarginTop: "3rem" },
  _4rem: { scrollMarginTop: "4rem" },
  _5rem: { scrollMarginTop: "5rem" },
  _6rem: { scrollMarginTop: "6rem" },
  _7rem: { scrollMarginTop: "7rem" },
  _8rem: { scrollMarginTop: "8rem" },
  _9rem: { scrollMarginTop: "9rem" },
});

