import * as stylex from "@stylexjs/stylex";

export const scrollPaddingLeft = stylex.create({
  _0: { scrollPaddingLeft: "0" },
  _0_125rem: { scrollPaddingLeft: "0.125rem" },
  _0_25rem: { scrollPaddingLeft: "0.25rem" },
  _0_375rem: { scrollPaddingLeft: "0.375rem" },
  _0_5rem: { scrollPaddingLeft: "0.5rem" },
  _0_625rem: { scrollPaddingLeft: "0.625rem" },
  _0_75rem: { scrollPaddingLeft: "0.75rem" },
  _0_875rem: { scrollPaddingLeft: "0.875rem" },
  _1_25rem: { scrollPaddingLeft: "1.25rem" },
  _1_5rem: { scrollPaddingLeft: "1.5rem" },
  _1_75rem: { scrollPaddingLeft: "1.75rem" },
  _10rem: { scrollPaddingLeft: "10rem" },
  _11rem: { scrollPaddingLeft: "11rem" },
  _12rem: { scrollPaddingLeft: "12rem" },
  _13rem: { scrollPaddingLeft: "13rem" },
  _14rem: { scrollPaddingLeft: "14rem" },
  _15rem: { scrollPaddingLeft: "15rem" },
  _16rem: { scrollPaddingLeft: "16rem" },
  _18rem: { scrollPaddingLeft: "18rem" },
  _1px: { scrollPaddingLeft: "1px" },
  _1rem: { scrollPaddingLeft: "1rem" },
  _2_25rem: { scrollPaddingLeft: "2.25rem" },
  _2_5rem: { scrollPaddingLeft: "2.5rem" },
  _2_75rem: { scrollPaddingLeft: "2.75rem" },
  _20rem: { scrollPaddingLeft: "20rem" },
  _24rem: { scrollPaddingLeft: "24rem" },
  _2rem: { scrollPaddingLeft: "2rem" },
  _3_5rem: { scrollPaddingLeft: "3.5rem" },
  _3rem: { scrollPaddingLeft: "3rem" },
  _4rem: { scrollPaddingLeft: "4rem" },
  _5rem: { scrollPaddingLeft: "5rem" },
  _6rem: { scrollPaddingLeft: "6rem" },
  _7rem: { scrollPaddingLeft: "7rem" },
  _8rem: { scrollPaddingLeft: "8rem" },
  _9rem: { scrollPaddingLeft: "9rem" },
});

