import * as stylex from "@stylexjs/stylex";

export const scrollPadding = stylex.create({
  _0: { scrollPadding: "0" },
  _0_125rem: { scrollPadding: "0.125rem" },
  _0_25rem: { scrollPadding: "0.25rem" },
  _0_375rem: { scrollPadding: "0.375rem" },
  _0_5rem: { scrollPadding: "0.5rem" },
  _0_625rem: { scrollPadding: "0.625rem" },
  _0_75rem: { scrollPadding: "0.75rem" },
  _0_875rem: { scrollPadding: "0.875rem" },
  _1_25rem: { scrollPadding: "1.25rem" },
  _1_5rem: { scrollPadding: "1.5rem" },
  _10rem: { scrollPadding: "10rem" },
  _11rem: { scrollPadding: "11rem" },
  _12rem: { scrollPadding: "12rem" },
  _13rem: { scrollPadding: "13rem" },
  _14rem: { scrollPadding: "14rem" },
  _16rem: { scrollPadding: "16rem" },
  _18rem: { scrollPadding: "18rem" },
  _1px: { scrollPadding: "1px" },
  _1rem: { scrollPadding: "1rem" },
  _2_5rem: { scrollPadding: "2.5rem" },
  _2_75rem: { scrollPadding: "2.75rem" },
  _20rem: { scrollPadding: "20rem" },
  _24rem: { scrollPadding: "24rem" },
  _2rem: { scrollPadding: "2rem" },
  _3_5rem: { scrollPadding: "3.5rem" },
  _3rem: { scrollPadding: "3rem" },
  _4rem: { scrollPadding: "4rem" },
  _5rem: { scrollPadding: "5rem" },
  _6rem: { scrollPadding: "6rem" },
  _7rem: { scrollPadding: "7rem" },
  _8rem: { scrollPadding: "8rem" },
  _9rem: { scrollPadding: "9rem" },
});

