import * as stylex from "@stylexjs/stylex";

export const scrollMarginBottom = stylex.create({
  _0: { scrollMarginBottom: "0" },
  _0_125rem: { scrollMarginBottom: "0.125rem" },
  _0_25rem: { scrollMarginBottom: "0.25rem" },
  _0_375rem: { scrollMarginBottom: "0.375rem" },
  _0_5rem: { scrollMarginBottom: "0.5rem" },
  _0_625rem: { scrollMarginBottom: "0.625rem" },
  _0_75rem: { scrollMarginBottom: "0.75rem" },
  _0_875rem: { scrollMarginBottom: "0.875rem" },
  _1_25rem: { scrollMarginBottom: "1.25rem" },
  _1_5rem: { scrollMarginBottom: "1.5rem" },
  _1_75rem: { scrollMarginBottom: "1.75rem" },
  _10rem: { scrollMarginBottom: "10rem" },
  _11rem: { scrollMarginBottom: "11rem" },
  _12rem: { scrollMarginBottom: "12rem" },
  _13rem: { scrollMarginBottom: "13rem" },
  _14rem: { scrollMarginBottom: "14rem" },
  _15rem: { scrollMarginBottom: "15rem" },
  _16rem: { scrollMarginBottom: "16rem" },
  _18rem: { scrollMarginBottom: "18rem" },
  _1px: { scrollMarginBottom: "1px" },
  _1rem: { scrollMarginBottom: "1rem" },
  _2_25rem: { scrollMarginBottom: "2.25rem" },
  _2_5rem: { scrollMarginBottom: "2.5rem" },
  _2_75rem: { scrollMarginBottom: "2.75rem" },
  _20rem: { scrollMarginBottom: "20rem" },
  _24rem: { scrollMarginBottom: "24rem" },
  _2rem: { scrollMarginBottom: "2rem" },
  _3_5rem: { scrollMarginBottom: "3.5rem" },
  _3rem: { scrollMarginBottom: "3rem" },
  _4rem: { scrollMarginBottom: "4rem" },
  _5rem: { scrollMarginBottom: "5rem" },
  _6rem: { scrollMarginBottom: "6rem" },
  _7rem: { scrollMarginBottom: "7rem" },
  _8rem: { scrollMarginBottom: "8rem" },
  _9rem: { scrollMarginBottom: "9rem" },
});

