import * as stylex from "@stylexjs/stylex";

export const scrollPaddingTop = stylex.create({
  _0: { scrollPaddingTop: "0" },
  _0_125rem: { scrollPaddingTop: "0.125rem" },
  _0_25rem: { scrollPaddingTop: "0.25rem" },
  _0_375rem: { scrollPaddingTop: "0.375rem" },
  _0_5rem: { scrollPaddingTop: "0.5rem" },
  _0_625rem: { scrollPaddingTop: "0.625rem" },
  _0_75rem: { scrollPaddingTop: "0.75rem" },
  _0_875rem: { scrollPaddingTop: "0.875rem" },
  _1_25rem: { scrollPaddingTop: "1.25rem" },
  _1_5rem: { scrollPaddingTop: "1.5rem" },
  _1_75rem: { scrollPaddingTop: "1.75rem" },
  _10rem: { scrollPaddingTop: "10rem" },
  _11rem: { scrollPaddingTop: "11rem" },
  _12rem: { scrollPaddingTop: "12rem" },
  _13rem: { scrollPaddingTop: "13rem" },
  _14rem: { scrollPaddingTop: "14rem" },
  _15rem: { scrollPaddingTop: "15rem" },
  _16rem: { scrollPaddingTop: "16rem" },
  _18rem: { scrollPaddingTop: "18rem" },
  _1px: { scrollPaddingTop: "1px" },
  _1rem: { scrollPaddingTop: "1rem" },
  _2_25rem: { scrollPaddingTop: "2.25rem" },
  _2_5rem: { scrollPaddingTop: "2.5rem" },
  _2_75rem: { scrollPaddingTop: "2.75rem" },
  _20rem: { scrollPaddingTop: "20rem" },
  _24rem: { scrollPaddingTop: "24rem" },
  _2rem: { scrollPaddingTop: "2rem" },
  _3_5rem: { scrollPaddingTop: "3.5rem" },
  _3rem: { scrollPaddingTop: "3rem" },
  _4rem: { scrollPaddingTop: "4rem" },
  _5rem: { scrollPaddingTop: "5rem" },
  _6rem: { scrollPaddingTop: "6rem" },
  _7rem: { scrollPaddingTop: "7rem" },
  _8rem: { scrollPaddingTop: "8rem" },
  _9rem: { scrollPaddingTop: "9rem" },
});

