import * as stylex from "@stylexjs/stylex";

export const scrollMarginLeft = stylex.create({
  _0: { scrollMarginLeft: "0" },
  _0_125rem: { scrollMarginLeft: "0.125rem" },
  _0_25rem: { scrollMarginLeft: "0.25rem" },
  _0_375rem: { scrollMarginLeft: "0.375rem" },
  _0_5rem: { scrollMarginLeft: "0.5rem" },
  _0_625rem: { scrollMarginLeft: "0.625rem" },
  _0_75rem: { scrollMarginLeft: "0.75rem" },
  _0_875rem: { scrollMarginLeft: "0.875rem" },
  _1_25rem: { scrollMarginLeft: "1.25rem" },
  _1_5rem: { scrollMarginLeft: "1.5rem" },
  _1_75rem: { scrollMarginLeft: "1.75rem" },
  _10rem: { scrollMarginLeft: "10rem" },
  _11rem: { scrollMarginLeft: "11rem" },
  _12rem: { scrollMarginLeft: "12rem" },
  _13rem: { scrollMarginLeft: "13rem" },
  _14rem: { scrollMarginLeft: "14rem" },
  _15rem: { scrollMarginLeft: "15rem" },
  _16rem: { scrollMarginLeft: "16rem" },
  _18rem: { scrollMarginLeft: "18rem" },
  _1px: { scrollMarginLeft: "1px" },
  _1rem: { scrollMarginLeft: "1rem" },
  _2_25rem: { scrollMarginLeft: "2.25rem" },
  _2_5rem: { scrollMarginLeft: "2.5rem" },
  _2_75rem: { scrollMarginLeft: "2.75rem" },
  _20rem: { scrollMarginLeft: "20rem" },
  _24rem: { scrollMarginLeft: "24rem" },
  _2rem: { scrollMarginLeft: "2rem" },
  _3_5rem: { scrollMarginLeft: "3.5rem" },
  _3rem: { scrollMarginLeft: "3rem" },
  _4rem: { scrollMarginLeft: "4rem" },
  _5rem: { scrollMarginLeft: "5rem" },
  _6rem: { scrollMarginLeft: "6rem" },
  _7rem: { scrollMarginLeft: "7rem" },
  _8rem: { scrollMarginLeft: "8rem" },
  _9rem: { scrollMarginLeft: "9rem" },
});

