import * as stylex from "@stylexjs/stylex";

export const scrollPaddingBottom = stylex.create({
  _0: { scrollPaddingBottom: "0" },
  _0_125rem: { scrollPaddingBottom: "0.125rem" },
  _0_25rem: { scrollPaddingBottom: "0.25rem" },
  _0_375rem: { scrollPaddingBottom: "0.375rem" },
  _0_5rem: { scrollPaddingBottom: "0.5rem" },
  _0_625rem: { scrollPaddingBottom: "0.625rem" },
  _0_75rem: { scrollPaddingBottom: "0.75rem" },
  _0_875rem: { scrollPaddingBottom: "0.875rem" },
  _1_25rem: { scrollPaddingBottom: "1.25rem" },
  _1_5rem: { scrollPaddingBottom: "1.5rem" },
  _1_75rem: { scrollPaddingBottom: "1.75rem" },
  _10rem: { scrollPaddingBottom: "10rem" },
  _11rem: { scrollPaddingBottom: "11rem" },
  _12rem: { scrollPaddingBottom: "12rem" },
  _13rem: { scrollPaddingBottom: "13rem" },
  _14rem: { scrollPaddingBottom: "14rem" },
  _15rem: { scrollPaddingBottom: "15rem" },
  _16rem: { scrollPaddingBottom: "16rem" },
  _18rem: { scrollPaddingBottom: "18rem" },
  _1px: { scrollPaddingBottom: "1px" },
  _1rem: { scrollPaddingBottom: "1rem" },
  _2_25rem: { scrollPaddingBottom: "2.25rem" },
  _2_5rem: { scrollPaddingBottom: "2.5rem" },
  _2_75rem: { scrollPaddingBottom: "2.75rem" },
  _20rem: { scrollPaddingBottom: "20rem" },
  _24rem: { scrollPaddingBottom: "24rem" },
  _2rem: { scrollPaddingBottom: "2rem" },
  _3_5rem: { scrollPaddingBottom: "3.5rem" },
  _3rem: { scrollPaddingBottom: "3rem" },
  _4rem: { scrollPaddingBottom: "4rem" },
  _5rem: { scrollPaddingBottom: "5rem" },
  _6rem: { scrollPaddingBottom: "6rem" },
  _7rem: { scrollPaddingBottom: "7rem" },
  _8rem: { scrollPaddingBottom: "8rem" },
  _9rem: { scrollPaddingBottom: "9rem" },
});

