import * as stylex from "@stylexjs/stylex";

export const scrollMarginRight = stylex.create({
  _0: { scrollMarginRight: "0" },
  _0_125rem: { scrollMarginRight: "0.125rem" },
  _0_25rem: { scrollMarginRight: "0.25rem" },
  _0_375rem: { scrollMarginRight: "0.375rem" },
  _0_5rem: { scrollMarginRight: "0.5rem" },
  _0_625rem: { scrollMarginRight: "0.625rem" },
  _0_75rem: { scrollMarginRight: "0.75rem" },
  _0_875rem: { scrollMarginRight: "0.875rem" },
  _1_25rem: { scrollMarginRight: "1.25rem" },
  _1_5rem: { scrollMarginRight: "1.5rem" },
  _1_75rem: { scrollMarginRight: "1.75rem" },
  _10rem: { scrollMarginRight: "10rem" },
  _11rem: { scrollMarginRight: "11rem" },
  _12rem: { scrollMarginRight: "12rem" },
  _13rem: { scrollMarginRight: "13rem" },
  _14rem: { scrollMarginRight: "14rem" },
  _15rem: { scrollMarginRight: "15rem" },
  _16rem: { scrollMarginRight: "16rem" },
  _18rem: { scrollMarginRight: "18rem" },
  _1px: { scrollMarginRight: "1px" },
  _1rem: { scrollMarginRight: "1rem" },
  _2_25rem: { scrollMarginRight: "2.25rem" },
  _2_5rem: { scrollMarginRight: "2.5rem" },
  _2_75rem: { scrollMarginRight: "2.75rem" },
  _20rem: { scrollMarginRight: "20rem" },
  _24rem: { scrollMarginRight: "24rem" },
  _2rem: { scrollMarginRight: "2rem" },
  _3_5rem: { scrollMarginRight: "3.5rem" },
  _3rem: { scrollMarginRight: "3rem" },
  _4rem: { scrollMarginRight: "4rem" },
  _5rem: { scrollMarginRight: "5rem" },
  _6rem: { scrollMarginRight: "6rem" },
  _7rem: { scrollMarginRight: "7rem" },
  _8rem: { scrollMarginRight: "8rem" },
  _9rem: { scrollMarginRight: "9rem" },
});

