import * as stylex from "@stylexjs/stylex";

export const scrollPaddingRight = stylex.create({
  _0: { scrollPaddingRight: "0" },
  _0_125rem: { scrollPaddingRight: "0.125rem" },
  _0_25rem: { scrollPaddingRight: "0.25rem" },
  _0_375rem: { scrollPaddingRight: "0.375rem" },
  _0_5rem: { scrollPaddingRight: "0.5rem" },
  _0_625rem: { scrollPaddingRight: "0.625rem" },
  _0_75rem: { scrollPaddingRight: "0.75rem" },
  _0_875rem: { scrollPaddingRight: "0.875rem" },
  _1_25rem: { scrollPaddingRight: "1.25rem" },
  _1_5rem: { scrollPaddingRight: "1.5rem" },
  _1_75rem: { scrollPaddingRight: "1.75rem" },
  _10rem: { scrollPaddingRight: "10rem" },
  _11rem: { scrollPaddingRight: "11rem" },
  _12rem: { scrollPaddingRight: "12rem" },
  _13rem: { scrollPaddingRight: "13rem" },
  _14rem: { scrollPaddingRight: "14rem" },
  _15rem: { scrollPaddingRight: "15rem" },
  _16rem: { scrollPaddingRight: "16rem" },
  _18rem: { scrollPaddingRight: "18rem" },
  _1px: { scrollPaddingRight: "1px" },
  _1rem: { scrollPaddingRight: "1rem" },
  _2_25rem: { scrollPaddingRight: "2.25rem" },
  _2_5rem: { scrollPaddingRight: "2.5rem" },
  _2_75rem: { scrollPaddingRight: "2.75rem" },
  _20rem: { scrollPaddingRight: "20rem" },
  _24rem: { scrollPaddingRight: "24rem" },
  _2rem: { scrollPaddingRight: "2rem" },
  _3_5rem: { scrollPaddingRight: "3.5rem" },
  _3rem: { scrollPaddingRight: "3rem" },
  _4rem: { scrollPaddingRight: "4rem" },
  _5rem: { scrollPaddingRight: "5rem" },
  _6rem: { scrollPaddingRight: "6rem" },
  _7rem: { scrollPaddingRight: "7rem" },
  _8rem: { scrollPaddingRight: "8rem" },
  _9rem: { scrollPaddingRight: "9rem" },
});

