/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { defineConfig } from "waku/config";
import mdx from "fumadocs-mdx/vite";
import * as MdxConfig from "./source.config.js";
import tsconfigPaths from "vite-tsconfig-paths";
import stylex from "@stylexjs/unplugin";
import type { Plugin } from "vite";
// import lightningcss from 'lightningcss';
import { browserslistToTargets } from "lightningcss";
import browserslist from "browserslist";

const require = createRequire(import.meta.url);
// Vite identifies runnable environments with instanceof. Resolve the helper
// from Waku's Vite instance so the RSC plugin recognizes the SSR environment.
const wakuRequire = createRequire(require.resolve("waku/config"));
const { createRunnableDevEnvironment } = wakuRequire(
  "vite",
) as typeof import("vite");
const __dirname = path.dirname(new URL(import.meta.url).pathname);

type ReactBabelOptions = {
  plugins: unknown[];
};

type ReactBabelContext = {
  ssr: boolean;
};

const reactCompilerPlugin: Plugin = {
  name: "stylextras:react-compiler",
  api: {
    reactBabel(babelConfig: ReactBabelOptions, context: ReactBabelContext) {
      if (!context.ssr) {
        babelConfig.plugins.push("babel-plugin-react-compiler");
      }
    },
  },
};

const playgroundSsrStubId = "\0stylextras:playground-ssr";
const playgroundSsrPlugin: Plugin = {
  name: "stylextras:playground-ssr",
  enforce: "pre",
  resolveId(id, importer, options) {
    if (
      options.ssr &&
      id === "./index" &&
      importer?.endsWith("/components/Playground/DynamicPlayground.tsx")
    ) {
      return playgroundSsrStubId;
    }
  },
  load(id) {
    if (id === playgroundSsrStubId) {
      return "export default function Playground() { return null; }";
    }
  },
};

const createFumadocsMdxPlugin = async (): Promise<Plugin> => {
  const plugin = await mdx(MdxConfig);
  const transform = plugin.transform;

  if (typeof transform !== "function") {
    return plugin;
  }

  return {
    ...plugin,
    async transform(code, id, options) {
      // These are JavaScript facades generated by @vitejs/plugin-rsc. Their
      // IDs retain the source .mdx suffix, but they must not be parsed as MDX.
      if (id.includes("virtual:vite-rsc/")) {
        return null;
      }
      return transform.call(this, code, id, options);
    },
  };
};

// Inline playground sources/types so Monaco and Sandpack can resolve them.
const playgroundDefines = (() => {
  const stylexFilename = require.resolve("@stylexjs/stylex");
  const stylexSource = fs.readFileSync(stylexFilename, "utf8");
  const stylexDir = path.dirname(stylexFilename);
  const stylexTypes: Record<string, string> = {};

  for (const file of fs.readdirSync(stylexDir, { recursive: true })) {
    const fileName = String(file);
    if (!fileName.endsWith(".d.ts")) {
      continue;
    }
    const normalizedFile = fileName.split(path.sep).join("/");
    stylexTypes[`file:///node_modules/@stylexjs/stylex/${normalizedFile}`] =
      fs.readFileSync(path.join(stylexDir, fileName), "utf8");
  }

  const reactTypesDir = path.dirname(
    require.resolve("@types/react/package.json"),
  );
  const reactTypes = fs.readFileSync(
    path.join(reactTypesDir, "index.d.ts"),
    "utf8",
  );
  const reactJsxRuntimeTypes = fs.readFileSync(
    path.join(reactTypesDir, "jsx-runtime.d.ts"),
    "utf8",
  );

  return {
    stylexSource,
    stylexTypes,
    reactTypes,
    reactJsxRuntimeTypes,
  };
})();

export default defineConfig({
  unstable_adapter: "waku/adapters/cloudflare",
  vite: {
    resolve: {
      // Keep hooks and renderers on one React dispatcher even when Bun's
      // cached peer links inside dependencies point at an older install.
      dedupe: ["react", "react-dom", "react-server-dom-webpack"],
    },
    environments: {
      ssr: {
        dev: {
          createEnvironment(name, config) {
            // Use the helper resolved from Waku above so its class identity
            // matches the environment checks inside @vitejs/plugin-rsc.
            return createRunnableDevEnvironment(name, config as never) as never;
          },
        },
      },
    },
    optimizeDeps: {
      exclude: ["@stylextras/ui"],
      include: [
        "@stylexjs/babel-plugin",
        "@babel/standalone",
        "use-query-params",
        "serialize-query-params",
        "path-browserify",
        "lz-string",
      ],
    },
    ssr: {
      // Force these CJS modules to be bundled during SSR so they work properly
      noExternal: [
        "@stylextras/ui",
        "use-query-params",
        "serialize-query-params",
      ],
      optimizeDeps: {
        include: ["use-query-params", "serialize-query-params"],
      },
    },
    define: {
      STYLEX_SOURCE: JSON.stringify(playgroundDefines.stylexSource),
      STYLEX_TYPES: JSON.stringify(playgroundDefines.stylexTypes),
      REACT_TYPES: JSON.stringify(playgroundDefines.reactTypes),
      REACT_JSX_RUNTIME_TYPES: JSON.stringify(
        playgroundDefines.reactJsxRuntimeTypes,
      ),
    },
    plugins: [
      reactCompilerPlugin,
      playgroundSsrPlugin,
      // @ts-ignore
      stylex.vite({
        debug: process.env.NODE_ENV === "development",
        treeshakeCompensation: true,
        enableDebugClassNames: false,
        enableDevClassNames: false,
        useCSSLayers: true,
        devMode: "css-only",
        devPersistToDisk: true,
        runtimeInjection: false,
        aliases: {
          "@/*": [path.join(__dirname, "src/*")],
        },
        lightningcssOptions: {
          minify: process.env.NODE_ENV !== "development",
          targets: browserslistToTargets(browserslist(">= 5%")),
        },
      }),
      // @ts-ignore
      createFumadocsMdxPlugin(),
      // @ts-ignore
      tsconfigPaths(),
    ],
  },
});
